# FROM node:12.18.3-alpine3.12
FROM node:14
# RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/iago/fundacao-certi-teste-programador/server
# home/node/app  
# 

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install

COPY . .

# COPY --chown=node:node . .
#USER node

EXPOSE 3000

CMD ["npm", "start"]
# CMD ["node", "server.js"]

# FROM node:12.18.1
# ENV NODE_ENV=production
# WORKDIR /app
# COPY ["package.json", "package-lock.json*", "./"]
# CMD [ "node", "server.js" ]
